# Generated by Django 5.2.7 on 2025-10-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pac', models.PositiveIntegerField()),
                ('nombre_pac', models.CharField(max_length=50)),
                ('apellido_pac', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_pac', models.CharField(max_length=15)),
                ('direccion_pac', models.CharField(max_length=100)),
                ('correo_pac', models.EmailField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
            ],
        ),
    ]
